### ISSUE TITLE
Working doc: revise issues

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-qe#125]
Here is the list of issues that should be fixed before making a production release of the QE app:

Bugs:

- [ ] Inform users if the required pseudos aren't available and allow for the automatic installation (#118).
- [ ] Could not create a water molecule with the SMILES structure generator (#115).
- [ ] The QE app crashes when reading QE input files (#108).
- [ ] Fix the Eiger configuration (https://github.com/aiidalab/aiidalab-qe/issues/105).
- [ ] When downloading an output file while the calculation is running, the downloaded file only contains the currently shown lines (#88).
- [ ] Update default `kpoints_distance` after changing the protocol (#59).

Features:
- [ ] Provide a list of k-points for the bandstructure calculations (#123).
- [ ] Add cell parameters to the structure viewer widget (https://github.com/aiidalab/aiidalab-widgets-base/issues/249)
- [ ] Add support for PdosWorkChain (https://github.com/aiidalab/aiidalab-qe/issues/62).
- [ ] Process list widget: add option 'all' to go back to the initial process list (which is the output like 'verdi process list -a').
- [ ] Allow for full editing of the QE input (#110), provide ccess to additional flags/override existing ones (#107).
- [ ] Improve bands structure plotting and e.g. reintroduce Dou's widget (https://github.com/aiidalab/aiidalab-qe/issues/104).
- [ ] Block the submission of calculations that would not actually do anything (#97).
- [ ] Make the output widget scrollable (#89).
- [ ] Improve dictionary visualization and download: allow to download the dictionary in JSON, make very large values in the dictionary collapsable (#86).
- [ ] Allow switching between the primitive and the conventional unit cells (#63).
- [ ] Add option to set smearing settings for ElectronicType.METAL (#64).
- [ ] Widget for setting magnetic configuration (#70).
- [ ] Add parallelization options to "Resources" tab (#83).
- [ ] Dealing with non-3D structures (#84).

User-friendliness:

- [ ] OPTIMADE client, the "Select provider choice" should be more visible (#121). Should be fixed by https://github.com/aiidalab/aiidalab-widgets-base/pull/247.
- [ ] Speed of the server startup, not it takes about 10 minutes (#112). Currently, it is slow because of the pseudos installation
- [ ] Improve visibility of the code/computer database (#102).
- [ ] Label a run so that the name will appear in the drop-down list associated with "Select workflow or start new: " (#102)
- [ ] Improve Workflow-Structure section to more clearly separate "Structure" from magnetism and electronic type, as well as make the selection more consistent (#102).
- [ ] Consider removing the "Expert mode" (#109).
- [ ] Give a better indication of what the work chain is doing as it is running (#113).
- [ ] Use user-friendly aliases for work chains and outputs (#87).
- [ ] Consider whether the layout is improved by placing the welcome text within a step/tab (#65).
- [ ] Replace the "Store in database" button with "Confirm" (#66).
- [ ] Add more information when selecting a work chain in the process tree (#68).
