### ISSUE TITLE
Summary of QeApp testing

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#242]
After the live testing with Nicola on 24th June, he and @mkotiuga give lots of valuable suggestions to improve the QeApp.
I summarize in this issue for different part of the widget respectively. 

### Optimade

Champions: Jusong @unkcpz 

- [ ]  The "Select provider" and "Apply filter" harder need to be more bigger so users know what the current step is and what they are supposed to do next.
- [ ] The OPTIMADE selection module steps should be numbered (e.g. "1. Select a provider" and so on).
- [ ] Add a "rocking message" that shows "Select provider" then changes to "Loading provider…" to the 2nd step.
- [ ] (WIP) The providers list clean up and move 'MC3D' and 'MC2D' to 'Main Projects' and others to 'Contribution Projects'. Drop 'SSSP' from list.
- [ ] (WIP) When database is chosen, the first query for max number of sites and elements caching moved from class to file and make a static file which will only be updated the next time deployed.
- [ ] The query results are show in the order of `nsites` not `id` as default. (Need to be check for other database whether the index are the same)
- [ ] The button to download all queried structures. https://github.com/CasperWA/voila-optimade-client/issues/233

### Structure selection

Champions: 

- [ ] The "Super Cell" widgets are too narrow on narrow screens.
- [ ] The appearance tab should be in front of the selection tab.
- [ ] The "Cell" tab is missing units (Angstrom).
 
### Workflow settings

Champions: 

- [ ] Ferromagnetic calculation should always run with the metallic settings. (occupations=fixed will not play nicely with setting a starting magnetization)
- [ ] Change selection to "Insulator", "Non-magnetic metal", "Ferromagnetic metal"; Also add a "Electronic structure" header. (Check the https://www.materialscloud.org/work/tools/qeinputgenerator. Could use the same label for the settings.)
- [ ] All selection elements should ideally be buttons to make the interface a bit more homogeneous, that means all exclusive choices are button groups and the "toggle" widgets that are currently check boxes become toggle buttons.
- [ ] For the properties to calculate if no properties are chosen a warning message is raised and blocks to go next step. It should be that even not selecting relaxation or bands or pdos should still run: then the user can still download the QE output file.
- [ ] (Copy from #102) Add feature to label each QeAppWorkChain, so they can be more easily found in the dropdown. #87 

### Status & Results

Champions:

- [ ] The "Summary View" should always be present, not only when you click on the "WorkChain" node.
- [ ] Final geometry: It should say "running" instead of "Not available" 
- [ ] Bug: The filename of the "Outputs" archive must have a .zip extension.
- [ ] There should be a "Status & Output" block showing a nice summary of what the work chain status is and also enable downloading the outputs. (https://github.com/aiidalab/aiidalab-qe/issues/113)

### Bands plot widget

Champions:

- [ ] Add a line at the zero level, but it should be indicated how the zero level was chosen (e.g. E-Ef). Or E_VBM for insulators.
- [ ] There should be tick marks (?).

### Text and description of every block

- [ ] Provide description texts to Nicola that are easy to edit and give feedback.

**Comment by unkcpz** [comment]
The issue is tracked all by the roadmap https://github.com/orgs/aiidalab/projects/7.
