### ISSUE TITLE
👌 IMPROVE: Minor layout and UX issues

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#53]
As I'm testing the QE app by trying to break stuff and tweaking the layout/content somewhat, I'm going to run into issues I don't immediately know how to fix, but want to keep track of. I'll keep these in this issue, and either try to fix them myself, or call in the cavalry (@csadorf and @yakutovicha).

- [x] Warning loads when opening the QE app that reads:

  > WARNING The pseudo potential families required for this app are not yet installed. In step 2: click on 'Pseudopotential', and then on 'Install pseudos' to install them.

  However, the "Pseudo potentials" tab (which I think [doesn't need to hyphenated](https://www.proofreadnow.com/blog/master-prefixes-and-suffixes-with-hyphens)) is only available in "expert" mode, so this warning will confuse laymen users.

  I think the SSSP pseudopotential libraries (or families) should be installed by default upon deployment, and the "Install pseudopotentials" button removed. Note that we also support the [Pseudo dojo](http://www.pseudo-dojo.org/) libraries in `aiida-pseudo` now, it might be interesting to extend the options users have here.

- [x] Codes are not configured, which is a bit of a hassle, especially when the user wants to run the `PdosWorkChain` to calculate the projected density of states and has to configure 3 codes.

  I think it's best to configure the default codes upon deployment.

- [x] The new tabs for expert mode aren't just added to the right, but some of them are inserted. That's a little weird, especially because it changes the active tab.

  <img src=https://filedn.com/lsOzB8TTUIDz2WkFj8o6qhp/aiidalab-qe/tabs_issue.gif width=500></img>

  I would just add the tabs on the right of the "layman" ones.

- [x] Consider having just one "Advanced options" tab. One issue is that the Functional choice is somewhat hidden in the "Pseudopotentials" tab. Although it is true that the pseudopotential files determine the functional, this is only because they are generated for specific functionals, so Quantum ESPRESSO reads the functional from the pseudopotential files header. However, the functional choice is quite fundamental in DFT, so I would put it front and center in an "Advanced options" tab.

  Perhaps we should just have one "Advanced Options" tab, whose UI is disabled by default. Something along the lines of what I was now working on for the "Pseudopotentials" tab:</br>
  <img src=https://filedn.com/lsOzB8TTUIDz2WkFj8o6qhp/aiidalab-qe/activate_gui.gif width=500></img></br>
 I think we can remove the "Expert mode" button for now, until we can think of more tabs that only experts need access to. Alternatively, we keep the expert mode and just remove the "Override" checkbox in the "Advanced options" tab. Though that would mean my hard work on adapting the opacity would be for naught. :sob:

- [x] Currently the "k-points distance" value widget disappears when "use default k-points" is checked:</br>
  <img src="https://filedn.com/lsOzB8TTUIDz2WkFj8o6qhp/aiidalab-qe/set_kpoints.gif" width=500></img></br>
  This is fancy, but I think it would be better if the user could see what the default k-points distance is here, without having to uncheck the box.

- [x] When I try to set the kpoints distance, it reverts back to the default, causing endless [frustration](https://i.kym-cdn.com/entries/icons/facebook/000/000/063/Rage.jpg):</br>
  <img src="https://filedn.com/lsOzB8TTUIDz2WkFj8o6qhp/aiidalab-qe/kpoints_distance.gif"></br>
  That should of course not happen. 😁 

- [x] Currently the "Select codes" tab is part of the "layman" tabs. However, if we install and set up the QE codes for the latest version by default, I think this should move into the expert mode tabs, and the codes should be configured to the defaults straight away.

- [x] Remove the install pseudos button. These should be installed by default, avoiding this hassle for the user.

- [x] Remove the "Use default X type" checkboxes for the spin and electronic type. Just put in the defaults and let them select the type.

- [x] Rephrase the work chain definition in terms of properties to calculate. 
- [x] Add an explanation to the new "Properties" section.
- [x]  Make the "POSITIONS_CELL" the default choice for the geometry optimization. @csadorf this refuses to work 😠 . I should just add a `value` argument to the `Dropdown`, no? Moved to #58
- [x] Remove the "Parameters" tab for now. I think this will be _very_ nice when the process builder can have a nice representation in HTML, sort of like here: https://github.com/aiidateam/aiida-core/pull/4970
- [x] Switch "Advanced Settings" and "Compute resources" tabs.

### Things to double check:

- [x] If the user untick the default k-points box and changes the k-points distance, then ticks the box again, is the default actually being used? Moved to #59 

### Questions

- [x] What purpose do the "Previous Step" and "Next Step" buttons serve? Are they outdated? EDIT: Seems you can indeed move between steps with them (but only "Next Step" seems to work?). I would remove this entire line of buttons. You can just click on the steps now, right? So why would you use these? The "Reset" button seems more important, but I'd instead have a nice big button on the top left or right that says "Start new workflow!". Moved to #56 

### Bugs to fix

- [x] When the user selects a protocol, the default values in the expert mode for e.g. the k-points distance should be updated. Moved to #59 
- [x] The structure is not showing in the "Final Geometry" tab of the outputs is not showing. Moved to #69 
- [x] The band structure is not showing either for some reason after I redeployed on my work station.

**Comment by mbercx** [comment]
Closed by #54
